# Generated by Django 3.0.5 on 2020-04-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='price',
            new_name='phone',
        ),
    ]
