# Generated by Django 3.0.5 on 2020-04-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200421_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='none',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
