# Generated by Django 3.0.5 on 2020-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
