# Generated by Django 3.0.5 on 2020-05-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200501_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out_of_delivery', 'out_of_delivery'), ('delivered', 'delivered')], max_length=200, null=True),
        ),
    ]
