# Generated by Django 3.0.5 on 2020-05-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200501_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
